services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - DATABASE_URL=postgres://postgres:postgres@db:5432/center_production
  #   ports:
  #     - 3000:3000
  db:
    # image: postgres:17-alpine
    build:
      context: ./pg_vector
      dockerfile: Dockerfile
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgres: